deployment:
  tasks:
    - export DEPLOYPATH=/home/pwki4027/manage.airhacklab.be
    - /bin/cp -a * $DEPLOYPATH
    - cd $DEPLOYPATH
    - php artisan down
    - php artisan migrate
    - composer update
    - php artisan cache:clear
    - php artisan up
